"""LLM prompt templates."""

from app.llms.prompts.templates import (
    SUPERVISOR_SYSTEM_PROMPT,
    RESEARCH_SYSTEM_PROMPT,
    PLANNER_SYSTEM_PROMPT,
    DATA_ANALYST_SYSTEM_PROMPT,
    CRITIC_SYSTEM_PROMPT,
    CODE_ASSISTANT_SYSTEM_PROMPT,
    AUTOMATION_SYSTEM_PROMPT,
    DOCUMENT_QA_SYSTEM_PROMPT,
    MEMORY_SYSTEM_PROMPT,
    GENERAL_SYSTEM_PROMPT,
    AGENT_PROMPTS,
    get_prompt,
)

__all__ = [
    "SUPERVISOR_SYSTEM_PROMPT",
    "RESEARCH_SYSTEM_PROMPT",
    "PLANNER_SYSTEM_PROMPT",
    "DATA_ANALYST_SYSTEM_PROMPT",
    "CRITIC_SYSTEM_PROMPT",
    "CODE_ASSISTANT_SYSTEM_PROMPT",
    "AUTOMATION_SYSTEM_PROMPT",
    "DOCUMENT_QA_SYSTEM_PROMPT",
    "MEMORY_SYSTEM_PROMPT",
    "GENERAL_SYSTEM_PROMPT",
    "AGENT_PROMPTS",
    "get_prompt",
]
