"""
Pydantic schemas package.

Exports all request/response schemas for API endpoints.
"""

from app.schemas.auth import (
    TokenResponse,
    TokenPayload,
    LoginRequest,
    RegisterRequest,
    RefreshTokenRequest,
    PasswordResetRequest,
    PasswordResetConfirm,
    ChangePasswordRequest,
    OAuthCallbackRequest,
)
from app.schemas.user import (
    UserBase,
    UserCreate,
    UserUpdate,
    UserResponse,
    UserDetail,
    UserList,
    UserSessionResponse,
    APIKeyCreate,
    APIKeyResponse,
    APIKeyCreated,
    AuditLogResponse,
    UserPreferencesUpdate,
)
from app.schemas.document import (
    DocumentCreate,
    DocumentUpdate,
    DocumentResponse,
    DocumentDetail,
    DocumentList,
    DocumentUploadResponse,
    DocumentChunkResponse,
    DocumentChunkList,
)
from app.schemas.knowledge_base import (
    KnowledgeBaseCreate,
    KnowledgeBaseUpdate,
    KnowledgeBaseResponse,
    KnowledgeBaseDetail,
    KnowledgeBaseList,
    KnowledgeBaseAddDocuments,
    KnowledgeBaseRemoveDocuments,
)
from app.schemas.chat import (
    ConversationCreate,
    ConversationUpdate,
    ConversationResponse,
    ConversationDetail,
    ConversationList,
    MessageCreate,
    MessageResponse,
    MessageList,
    ChatRequest,
    ChatResponse,
    ChatStreamEvent,
    ConversationBookmarkCreate,
    ConversationBookmarkResponse,
)
from app.schemas.memory import (
    MemoryEntryCreate,
    MemoryEntryUpdate,
    MemoryEntryResponse,
    MemoryEntryList,
    UserPreferenceUpdate,
    UserPreferenceResponse,
    UserPreferenceList,
)
from app.schemas.workflow import (
    WorkflowCreate,
    WorkflowUpdate,
    WorkflowResponse,
    WorkflowDetail,
    WorkflowList,
    WorkflowExecuteRequest,
    WorkflowExecutionResponse,
    WorkflowExecutionList,
    WorkflowStepExecutionResponse,
)
from app.schemas.agent import (
    AgentConfigurationCreate,
    AgentConfigurationUpdate,
    AgentConfigurationResponse,
    AgentConfigurationDetail,
    AgentConfigurationList,
    AgentExecuteRequest,
    AgentExecuteResponse,
)
from app.schemas.task import (
    TaskResponse,
    TaskList,
    TaskCancelRequest,
)
from app.schemas.analytics import (
    AnalyticsReportCreate,
    AnalyticsReportResponse,
    AnalyticsReportList,
    VisualizationCreate,
    VisualizationResponse,
    VisualizationList,
    UserActivityResponse,
    UserActivityList,
    AnalyticsSummary,
)
from app.schemas.common import (
    PaginationParams,
    SortParams,
    FilterParams,
    SuccessResponse,
    ErrorResponse,
    ErrorDetail,
    HealthCheckResponse,
    MetricsResponse,
)

__all__ = [
    # Auth
    "TokenResponse",
    "TokenPayload",
    "LoginRequest",
    "RegisterRequest",
    "RefreshTokenRequest",
    "PasswordResetRequest",
    "PasswordResetConfirm",
    "ChangePasswordRequest",
    "OAuthCallbackRequest",
    # User
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    "UserDetail",
    "UserList",
    "UserSessionResponse",
    "APIKeyCreate",
    "APIKeyResponse",
    "APIKeyCreated",
    "AuditLogResponse",
    "UserPreferencesUpdate",
    # Document
    "DocumentCreate",
    "DocumentUpdate",
    "DocumentResponse",
    "DocumentDetail",
    "DocumentList",
    "DocumentUploadResponse",
    "DocumentChunkResponse",
    "DocumentChunkList",
    # Knowledge Base
    "KnowledgeBaseCreate",
    "KnowledgeBaseUpdate",
    "KnowledgeBaseResponse",
    "KnowledgeBaseDetail",
    "KnowledgeBaseList",
    "KnowledgeBaseAddDocuments",
    "KnowledgeBaseRemoveDocuments",
    # Chat
    "ConversationCreate",
    "ConversationUpdate",
    "ConversationResponse",
    "ConversationDetail",
    "ConversationList",
    "MessageCreate",
    "MessageResponse",
    "MessageList",
    "ChatRequest",
    "ChatResponse",
    "ChatStreamEvent",
    "ConversationBookmarkCreate",
    "ConversationBookmarkResponse",
    # Memory
    "MemoryEntryCreate",
    "MemoryEntryUpdate",
    "MemoryEntryResponse",
    "MemoryEntryList",
    "UserPreferenceUpdate",
    "UserPreferenceResponse",
    "UserPreferenceList",
    # Workflow
    "WorkflowCreate",
    "WorkflowUpdate",
    "WorkflowResponse",
    "WorkflowDetail",
    "WorkflowList",
    "WorkflowExecuteRequest",
    "WorkflowExecutionResponse",
    "WorkflowExecutionList",
    "WorkflowStepExecutionResponse",
    # Agent
    "AgentConfigurationCreate",
    "AgentConfigurationUpdate",
    "AgentConfigurationResponse",
    "AgentConfigurationDetail",
    "AgentConfigurationList",
    "AgentExecuteRequest",
    "AgentExecuteResponse",
    # Task
    "TaskResponse",
    "TaskList",
    "TaskCancelRequest",
    # Analytics
    "AnalyticsReportCreate",
    "AnalyticsReportResponse",
    "AnalyticsReportList",
    "VisualizationCreate",
    "VisualizationResponse",
    "VisualizationList",
    "UserActivityResponse",
    "UserActivityList",
    "AnalyticsSummary",
    # Common
    "PaginationParams",
    "SortParams",
    "FilterParams",
    "SuccessResponse",
    "ErrorResponse",
    "ErrorDetail",
    "HealthCheckResponse",
    "MetricsResponse",
]
