export const CURRENCY_CONFIG = {
  USD: {
    symbol: "$",
    locale: "en-US",
    decimalPlaces: 2,
    thousandsSeparator: ",",
    decimalSeparator: ".",
    symbolPosition: "before" as const,
  },
  INR: {
    symbol: "\u20B9",
    locale: "en-IN",
    decimalPlaces: 2,
    thousandsSeparator: ",",
    decimalSeparator: ".",
    symbolPosition: "before" as const,
  },
  EUR: {
    symbol: "\u20AC",
    locale: "de-DE",
    decimalPlaces: 2,
    thousandsSeparator: ".",
    decimalSeparator: ",",
    symbolPosition: "before" as const,
  },
  GBP: {
    symbol: "\u00A3",
    locale: "en-GB",
    decimalPlaces: 2,
    thousandsSeparator: ",",
    decimalSeparator: ".",
    symbolPosition: "before" as const,
  },
  AUD: {
    symbol: "A$",
    locale: "en-AU",
    decimalPlaces: 2,
    thousandsSeparator: ",",
    decimalSeparator: ".",
    symbolPosition: "before" as const,
  },
  CAD: {
    symbol: "C$",
    locale: "en-CA",
    decimalPlaces: 2,
    thousandsSeparator: ",",
    decimalSeparator: ".",
    symbolPosition: "before" as const,
  },
  JPY: {
    symbol: "\u00A5",
    locale: "ja-JP",
    decimalPlaces: 0,
    thousandsSeparator: ",",
    decimalSeparator: ".",
    symbolPosition: "before" as const,
  },
} as const;

export type CurrencyCode = keyof typeof CURRENCY_CONFIG;

export const COUNTRY_CURRENCY_MAP: Record<string, CurrencyCode> = {
  US: "USD",
  IN: "INR",
  GB: "GBP",
  DE: "EUR",
  FR: "EUR",
  IT: "EUR",
  ES: "EUR",
  NL: "EUR",
  BE: "EUR",
  AT: "EUR",
  IE: "EUR",
  PT: "EUR",
  FI: "EUR",
  GR: "EUR",
  LU: "EUR",
  AU: "AUD",
  CA: "CAD",
  JP: "JPY",
  SG: "USD",
  AE: "USD",
  SA: "USD",
  BR: "USD",
  MX: "USD",
  ZA: "USD",
  NG: "USD",
  KE: "USD",
  PH: "USD",
  MY: "USD",
  TH: "USD",
  VN: "USD",
  ID: "USD",
  KR: "USD",
  TW: "USD",
  HK: "USD",
  NZ: "USD",
  CH: "EUR",
  SE: "EUR",
  NO: "EUR",
  DK: "EUR",
  PL: "EUR",
  CZ: "EUR",
  RO: "EUR",
  HU: "EUR",
  BG: "EUR",
};

export const DEFAULT_CURRENCY: CurrencyCode = "USD";
export const DEFAULT_COUNTRY = "US";

export const PLAN_LIMITS = {
  free: {
    messages: 50,
    documents: 10,
    knowledgeBases: 1,
    agents: 1,
    storageBytes: 500 * 1024 * 1024, // 500MB
  },
  pro: {
    messages: 1000,
    documents: 100,
    knowledgeBases: 10,
    agents: 5,
    storageBytes: 10 * 1024 * 1024 * 1024, // 10GB
  },
  enterprise: {
    messages: -1, // unlimited
    documents: -1,
    knowledgeBases: -1,
    agents: -1,
    storageBytes: -1,
  },
} as const;

export const PLAN_FEATURES = {
  free: [
    { label: "50 AI messages/month", included: true },
    { label: "10 documents", included: true },
    { label: "1 knowledge base", included: true },
    { label: "1 AI agent", included: true },
    { label: "Basic analytics", included: true },
    { label: "Community support", included: true },
    { label: "Custom AI models", included: false },
    { label: "API access", included: false },
    { label: "SSO & team management", included: false },
    { label: "Dedicated support", included: false },
    { label: "SLA guarantee", included: false },
  ],
  pro: [
    { label: "1,000 AI messages/month", included: true },
    { label: "100 documents", included: true },
    { label: "10 knowledge bases", included: true },
    { label: "5 AI agents", included: true },
    { label: "Advanced analytics & reports", included: true },
    { label: "Priority support", included: true },
    { label: "Custom AI models", included: true },
    { label: "API access", included: true },
    { label: "SSO & team management", included: false },
    { label: "Dedicated support", included: false },
    { label: "SLA guarantee", included: false },
  ],
  enterprise: [
    { label: "Unlimited AI messages", included: true },
    { label: "Unlimited documents", included: true },
    { label: "Unlimited knowledge bases", included: true },
    { label: "Unlimited AI agents", included: true },
    { label: "Custom analytics dashboards", included: true },
    { label: "Dedicated support", included: true },
    { label: "Custom AI models", included: true },
    { label: "Full API access", included: true },
    { label: "SSO & team management", included: true },
    { label: "SLA guarantee", included: true },
  ],
} as const;
